[build.environment]
  NODE_VERSION = "16"

[build]
  command = "npm run generate"
  publish = "dist"

[[redirects]]
  from = "https://nuxt.mvsde.com/*"
  to = "https://nuxt.talks.fynn.be/:splat"
  force = true
